/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import javax.swing.JOptionPane;
public class Data extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nim = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Cari Data Berdasarkan NIM Mahasiswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("NIM");

        jLabel3.setText("Nama");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(33, 33, 33)
                                .addComponent(exit))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nim)
                                .addComponent(nama1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(exit))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       //ini program mencari jenis kelamin
       String kodeNim = nim.getText();
       
       String nama = nama1.getText();
       
       char jeKelamin = kodeNim.charAt(6);
       
       JOptionPane.showMessageDialog(this, "Nama Mahasiswa : " + nama);
       
       if(jeKelamin == '1')
       {
           JOptionPane.showMessageDialog(this, "Jenis Kelamin mahasiswa adalah Laki-Laki");
       }else if (jeKelamin == '2')
       {
           JOptionPane.showMessageDialog(this, "Jenis Kelamin mahasiswa adalah Perempuan");
       }else
       {
           JOptionPane.showMessageDialog(this, "Jenis Kelamin Tidak Ditemukan");
       }
       
       //ini adalah code program mencari kode urut mahasiswa
       String kodeUrut = kodeNim.substring(7);
       
       JOptionPane.showMessageDialog(this, "Kode Urut Mahasiswa Anda Adalah :" + kodeUrut);
       
       
       //ini adalah code program untuk jenjang pendidikan
       char koJenj = kodeNim.charAt(0);
       
       if(koJenj == '1')
       {
           JOptionPane.showMessageDialog(this, "Jenjang S-1");
       }else if (koJenj == '2')
       {
           JOptionPane.showMessageDialog(this, "Jenjang S-2");
       }else if(koJenj == '3')
       {
           JOptionPane.showMessageDialog(this, "Jenjang S-3");
       }
       
       //ini adalah kode tahun masuk
       String tahun = kodeNim.substring(1,3);
       
       if(tahun.equals("20"))
       {
          JOptionPane.showMessageDialog(this, "Mahasiswa Tahun 2020");
       }else if(tahun.equals("19"))
       {
           JOptionPane.showMessageDialog(this, "Mahasiswa Tahun 2019  ");
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Upps, tahun masuk tidak ditemukan");
       }
       
       //ini adalah kode untuk jurusan
       String jurusan = kodeNim.substring(4, 6);
       
       if(jurusan.equals("01"))
       {
          JOptionPane.showMessageDialog(this, "Teknik Informatika");
          
       }else if(jurusan.equals("02"))
       {
           JOptionPane.showMessageDialog(this, "Teknik Industri");
       }
       else if(jurusan.equals("03"))
       {
           JOptionPane.showMessageDialog(this, "Sistem Informasi");
       }
       else if(jurusan.equals("04"))
       {
           JOptionPane.showMessageDialog(this, "Matematika");
       }
       else if(jurusan.equals("05"))
       {
           JOptionPane.showMessageDialog(this, "Elektro");
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Upps, jurusan tidak ditemukan");
       }
       
       //kode untuk fakultas
       
       char fakultas = kodeNim.charAt(3);
       
       if(fakultas == '1')
       {
           JOptionPane.showMessageDialog(this, "Tarbiyah dan Keguruan");
       }else if (fakultas == '2')
       {
           JOptionPane.showMessageDialog(this, "Syariah dan Hukum");
       }else if (fakultas == '3')
       {
           JOptionPane.showMessageDialog(this, "USHULUDDIN");
       }
       else if (fakultas == '4')
       {
           JOptionPane.showMessageDialog(this, "Dakwah dan Komunikasi");
       }
       else if (fakultas == '5')
       {
           JOptionPane.showMessageDialog(this, "Sains dan Teknologi");
           //System.out.println("Sains dan Teknologi");
       }
       else if (fakultas == '6')
       {
           JOptionPane.showMessageDialog(this, "Psikologi");
       }
       else if (fakultas == '7')
       {
           JOptionPane.showMessageDialog(this, "Ekonomi dan Ilmu Social");
       }
       else if (fakultas == '8')
       {
           JOptionPane.showMessageDialog(this, "Pertanian dan Peternakana");
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Jenis Kelamin Tidak Ditemukan");
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextField nim;
    // End of variables declaration//GEN-END:variables
}
